=== shaharben/EmpireForge/docs/Modders/schemas/CityStateTypes.schema.json
{
  "$id": "https://raw.githubusercontent.com/yairm210/Unciv/refs/heads/master/docs/Modders/schemas/CityStateTypes.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "CityStateTypes",
  "description": "A list of city state types, including their bonuses and color information.",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "name": {
        "type": "string",
        "title": "Name",
        "description": "The name of the City State Type.",
        "examples": [
          "Cultured",
          "Maritime",
          "Mercantile",
          "Militaristic",
          "Strategic"
        ]
      },
      "friendBonusUniques": {
        "$ref": "refs/Uniques.schema.json",
        "title": "Friend Bonus Uniques",
        "description": "List of unique abilities granted to major civilizations when friends with this city state"
      },
      "allyBonusUniques": {
        "$ref": "refs/Uniques.schema.json",
        "title": "Ally Bonus Uniques",
        "description": "List of unique abilities granted to major civilizations when allied to city state"
      },
      "color": {
        "$ref": "refs/Color.schema.json",
        "description": "RGB color of text in civilopedia",
        "default": [255, 255, 255]
      }
    },
    "required": ["name"],
    "additionalProperties": false
  }
}

=== shaharben/EmpireForge/android/assets/jsons/Civ V - Gods & Kings/CityStateTypes.json
[
    {
        "name": "Knowledge",
        "friendBonusUniques": [
            "[+3 Culture] <before the [Fortress Era]>",
            "[+6 Culture] <starting from the [Fortress Era]> <before the [Reconstruction Era]>",
            "[+13 Culture] <starting from the [Reconstruction Era]>"
        ],
        "allyBonusUniques": [
            "[+6 Culture] <before the [Fortress Era]>",
            "[+12 Culture] <starting from the [Fortress Era]> <before the [Reconstruction Era]>",
            "[+26 Culture] <starting from the [Reconstruction Era]>"
        ],
        "color": [139, 96, 255]
    },
    {
        "name": "Harbor",
        "friendBonusUniques": ["[+2 Food] [in capital]"],
        "allyBonusUniques": ["[+2 Food] [in capital]", "[+1 Food] [in all cities]"],
        "color": [56, 255, 112]
    },
    {
        "name": "Trade Post",
        "friendBonusUniques": [
            "[+2 Happiness] <before the [Fortress Era]>",
            "[+3 Happiness] <starting from the [Fortress Era]>"
        ],
        "allyBonusUniques": [
            "[+2 Happiness] <before the [Fortress Era]>",
            "[+3 Happiness] <starting from the [Fortress Era]>",
            "Provides a unique luxury"
        ],
        "color": [255, 216, 0]
    },
    {
        "name": "Militia",
        "friendBonusUniques": ["Provides military units every ≈[20] turns"],
        "allyBonusUniques": ["Provides military units every ≈[17] turns"],
        "color": [255, 0, 0]
    },
    {
        "name": "Technical",
        "friendBonusUniques":  [
            "[+3 Faith] <before the [Fortress Era]>",
            "[+6 Faith] <starting from the [Fortress Era]> <before the [Reconstruction Era]>",
            "[+13 Faith] <starting from the [Reconstruction Era]>"
        ],
        "allyBonusUniques":  [
            "[+6 Faith] <before the [Fortress Era]>",
            "[+12 Faith] <starting from the [Fortress Era]> <before the [Reconstruction Era]>",
            "[+26 Faith] <starting from the [Reconstruction Era]>"
        ],
        "color": [255, 255, 255]
    }
]
