=== shaharben/EmpireForge/docs/Modders/schemas/Speeds.schema.json
{
  "$id": "https://raw.githubusercontent.com/yairm210/Unciv/refs/heads/master/docs/Modders/schemas/Speeds.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Speeds",
  "description": "A list of available game speeds.",
  "type": "array",
  "items": {
    "type": "object",
    "required": ["name", "turns"],
    "properties": {
      "name": {
        "type": "string",
        "title": "Name",
        "description": "Name of the speed."
      },
      "modifier": {
        "type": "number",
        "minimum": 0,
        "default": 1.0,
        "title": "Modifier",
        "description": "Overall game speed modifier."
      },
      "productionCostModifier": {
        "type": "number",
        "minimum": 0,
        "title": "Production Cost Modifier",
        "description": "Scales production cost of units and buildings."
      },
      "goldCostModifier": {
        "type": "number",
        "minimum": 0,
        "title": "Gold Cost Modifier",
        "description": "Scales gold costs."
      },
      "scienceCostModifier": {
        "type": "number",
        "minimum": 0,
        "title": "Science Cost Modifier",
        "description": "Scales science costs."
      },
      "cultureCostModifier": {
        "type": "number",
        "minimum": 0,
        "title": "Culture Cost Modifier",
        "description": "Scales culture costs."
      },
      "authorityCostModifier": {
        "type": "number",
        "minimum": 0,
        "title": "Authority Cost Modifier",
        "description": "Scales authority costs."
      },
      "improvementBuildLengthModifier": {
        "type": "number",
        "minimum": 0,
        "title": "Improvement Build Length Modifier",
        "description": "Scales the time it takes for a worker to build tile improvements."
      },
      "barbarianModifier": {
        "type": "number",
        "minimum": 0,
        "title": "Barbarian Modifier",
        "description": "Scales the time between barbarian spawns."
      },
      "goldGiftModifier": {
        "type": "number",
        "minimum": 0,
        "title": "Gold Gift Modifier",
        "description": "Scales the influence gained from gifting gold to city-states."
      },
      "cityStateTributeScalingInterval": {
        "type": "number",
        "minimum": 0,
        "default": 6.5,
        "title": "City-State Tribute Scaling Interval",
        "description": "Turns for city-state tribute scaling."
      },
      "goldenAgeLengthModifier": {
        "type": "number",
        "minimum": 0,
        "title": "Golden Age Length Modifier",
        "description": "Scales the length of golden ages."
      },
      "religiousPressureAdjacentCity": {
        "type": "integer",
        "minimum": 0,
        "default": 6,
        "title": "Strategic Pressure Adjacent City",
        "description": "Strategic pressure exerted on nearby cities."
      },
      "peaceDealDuration": {
        "type": "integer",
        "minimum": 0,
        "default": 10,
        "title": "Peace Deal Duration",
        "description": "Turns a peace deal lasts."
      },
      "dealDuration": {
        "type": "integer",
        "minimum": 0,
        "default": 30,
        "title": "Deal Duration",
        "description": "Turns a non-peace deal lasts."
      },
      "startYear": {
        "type": "number",
        "default": -4000,
        "title": "Start Year",
        "description": "Start year of the game."
      },
      "turns": {
        "type": "array",
        "title": "Turns",
        "description": "List of time intervals per turn. Each object defines the years per turn and the turn interval.",
        "items": {
          "type": "object",
          "required": ["yearsPerTurn", "untilTurn"],
          "properties": {
            "yearsPerTurn": {
              "type": "number",
              "title": "Years Per Turn",
              "description": "Number of years passing between turns.",
              "minimum": 0
            },
            "untilTurn": {
              "type": "integer",
              "title": "Until Turn",
              "description": "End of this interval (if it is the last object, only used for Era.startPercent).",
              "minimum": 0
            }
          },
          "additionalProperties": false
        }
      },
      "uniques": {
        "$ref": "refs/Uniques.schema.json"
      },
      "civilopediaText": {
        "$ref": "refs/CivilopediaText.schema.json"
      }
    },
    "additionalProperties": false
  }
}

=== shaharben/EmpireForge/android/assets/jsons/Civ V - Vanilla/Speeds.json
[
    {
        "name": "Blitz",
        "modifier": 0.67,
        "productionCostModifier": 0.67,
        "goldCostModifier": 0.67,
        "scienceCostModifier": 0.67,
        "cultureCostModifier": 0.67,

        "improvementBuildLengthModifier": 0.67,
        "barbarianModifier": 0.67,
        "goldGiftModifier": 1.25,
        "cityStateTributeScalingInterval": 5.0,
        "goldenAgeLengthModifier": 0.80,

        "peaceDealDuration": 10,
        "dealDuration": 25,
        "startYear": -4000,
        "turns": [
            {"yearsPerTurn": 60, "untilTurn":  50},
            {"yearsPerTurn": 40, "untilTurn":  80},
            {"yearsPerTurn": 30, "untilTurn": 100},
            {"yearsPerTurn": 20, "untilTurn": 130},
            {"yearsPerTurn": 10, "untilTurn": 155},
            {"yearsPerTurn":  5, "untilTurn": 195},
            {"yearsPerTurn":  2, "untilTurn": 260},
            {"yearsPerTurn":  1, "untilTurn": 330}
        ]
    },
    {
        "name": "Normal",
        "modifier": 1.0,
        "productionCostModifier": 1.0,
        "goldCostModifier": 1.0,
        "scienceCostModifier": 1.0,
        "cultureCostModifier": 1.0,

        "improvementBuildLengthModifier": 1.0,
        "barbarianModifier": 1.0,
        "goldGiftModifier": 1.0,
        "cityStateTributeScalingInterval": 6.5,
        "goldenAgeLengthModifier": 1.0,

        "peaceDealDuration": 10,
        "dealDuration": 30,
        "startYear": -4000,
        "turns": [
            {"yearsPerTurn":  40, "untilTurn": 75},
            {"yearsPerTurn":  25, "untilTurn": 135},
            {"yearsPerTurn":  20, "untilTurn": 160},
            {"yearsPerTurn":  10, "untilTurn": 210},
            {"yearsPerTurn":   5, "untilTurn": 270},
            {"yearsPerTurn":   2, "untilTurn": 320},
            {"yearsPerTurn":   1, "untilTurn": 440},
            {"yearsPerTurn": 0.5, "untilTurn": 500}
        ]
    },
    {
        "name": "Extended",
        "modifier": 1.5,
        "productionCostModifier": 1.5,
        "goldCostModifier": 1.5,
        "scienceCostModifier": 1.5,
        "cultureCostModifier": 1.5,

        "improvementBuildLengthModifier": 1.5,
        "barbarianModifier": 1.5,
        "goldGiftModifier": 0.75,
        "cityStateTributeScalingInterval": 14.0,
        "goldenAgeLengthModifier": 1.25,

        "peaceDealDuration": 15,
        "dealDuration": 45,
        "startYear": -4000,
        "turns": [
            {"yearsPerTurn":  25, "untilTurn": 140},
            {"yearsPerTurn":  15, "untilTurn": 230},
            {"yearsPerTurn":  10, "untilTurn": 270},
            {"yearsPerTurn":   5, "untilTurn": 360},
            {"yearsPerTurn":   2, "untilTurn": 430},
            {"yearsPerTurn":   1, "untilTurn": 530},
            {"yearsPerTurn": 0.5, "untilTurn": 750}
        ]
    },
    {
        "name": "Endurance",
        "modifier": 3.0,
        "productionCostModifier": 3.0,
        "goldCostModifier": 3.0,
        "scienceCostModifier": 3.0,
        "cultureCostModifier": 3.0,

        "improvementBuildLengthModifier": 3.0,
        "barbarianModifier": 4.0,
        "goldGiftModifier": 0.67,
        "cityStateTributeScalingInterval": 32.0,
        "goldenAgeLengthModifier": 2.0,

        "peaceDealDuration": 30,
        "dealDuration": 90,
        "startYear": -4000,
        "turns": [
            {"yearsPerTurn":   15,     "untilTurn":  100},
            {"yearsPerTurn":   10,     "untilTurn":  400},
            {"yearsPerTurn":    5,     "untilTurn":  570},
            {"yearsPerTurn":    2,     "untilTurn":  771},
            {"yearsPerTurn":    1,     "untilTurn":  900},
            {"yearsPerTurn":  0.5,     "untilTurn": 1080},
            {"yearsPerTurn": 0.25,     "untilTurn": 1344},
            {"yearsPerTurn": 0.083333, "untilTurn": 1500}
        ]
    }
]
